protokol_okw = {
    "start": [
        { "sub": "entries", "field": "data", "template": "templ_proto" }
    ],
    "entries": [
        { "field": "sin", "num": "xin","type": "longnum", "pri": 0, "ro": 1, "text": "Xin" },
        { "heading": "Dane ogólne", "copy": "submitOuter" },
        { "field": "rola", "num": "D1", "pri": 1, "type": "rola", "text": "Funkcja zgłaszającego" },
        { "field": "imie", "num": "D2", "pri": 1, "type": "text", "text": "Imię" },
        { "field": "nazwisko", "num": "D3", "pri": 1, "type": "text", "text": "Nazwisko" },

        { "field": "obserwacja_przyg_lokalu", "num": "D5", "pri": 1, "type": "bool+czas+text", "text": "Obserwacja przygotowania lokalu" },
        { "field": "obserwacja_glosowania", "num": "D6", "pri": 1, "type": "bool+czas+text", "text": "Obserwacja głosowania" },
        { "field": "obserwacja_liczenia", "num": "D7", "pri": 1, "type": "bool+czas+text", "text": "Obserwacja liczenia głosów" },
        { "heading": "Dane o komisji (szare) wypełnione automatycznie, bez edycji", "copy": "submitOuter" },
        
        { "field": "woj", "num": "D8", "pri": 1, "ro": 1, "type": "text", "text": "Województwo" },
        { "field": "gmina", "num": "D9", "pri": 1, "ro": 1, "type": "text", "text": "Gmina" },
        { "field": "num_obw", "num": "D10", "pri": 11, "ro": 1, "text": "Nr obwodowej komisji wyborczej <br> (aby zmienić - pójdź na górę strony)" },
        { "field": "adres", "num": "D11", "pri": 1, "ro": 1, "type": "text", "text": "Adres komisji" },
        { "field": "siedziba_opis", "num": "D12", "pri": 1, "ro": 1, "type": "text", "text": "Miejsce - opis szczegółowy" },
        { "field": "komisja_czlonkow", "num": "D13", "pri": 1, "text": "Liczba członków komisji" },
        { "field": "komisja_osob_upr", "num": "D14", "pri": 1, "text": "Liczba osób uprawnionych do głosowania w komisji" },
        { "heading": "Przygotowanie", "copy": "submitOuter" },
        { "field": "P1", "num": "P1", "pri": 1, "type": "bool+text", "text": "Czy komisja jest prawidłowo oznaczona – na zewnątrz i wewnątrz lokalu wyborczego?", "info": "Jeżeli nie to dlaczego?" },
        { "field": "P2", "num": "P2", "pri": 1, "type": "bool+text", "text": "Czy po opieczętowaniu karty były przechowywane w taki sposób, aby nie miała do nich dostępu żadna osoba nieuprawniona?", "info": "Jeżeli nie to dlaczego?" },
        { "field": "P3", "num": "P3", "pri": 1, "type": "bool+text", "text": "Czy w lokalu wyborczym znajdują się wymagane obwieszczenia i informacje o sposobie głosowania?", "info": "Jeżeli nie to dlaczego?" },
        { "field": "P4", "num": "P4", "pri": 1, "type": "bool+text", "text": "Czy w lokalu wyborczym znajdują się miejsca zapewniające tajność głosowania?", "info": "Jeżeli nie to dlaczego?" },
        { "field": "P5", "num": "P5", "pri": 1, "type": "bool+text", "text": "Czy w lokalu wyborczym lub na terenie, na którym się on znajduje znaleziono jakiekolwiek materiały agitacyjne?", "info": "Jeżeli tak, to jakie i co z nimi zrobiono?" },
        { "field": "P6", "num": "P6", "pri": 1, "type": "bool+text", "text": "Czy komisja w jakimkolwiek momencie utrudniała Ci obserwację procedury przygotowania lokalu wyborczego do głosowania?", "info": "Jeżeli tak, opisz na czym polegały utrudnienia:" },
        { "field": "P7", "num": "P7", "pri": 1, "type": "bool+text", "text": "Czy zgłaszałeś komisji uwagi do sposobu jej pracy?", "info": "Jeśli tak, to jakie uwagi i jaka była reakcja członków Komisji?" },
        { "field": "P8", "num": "P8", "pri": 1, "type": "ocena", "text": "Ogólna ocena pracy komisji podczas przygotowania" },
        { "field": "P9", "num": "P9", "pri": 1, "type": "textarea", "text": "Dodatkowe komentarze (dot. przygotowania)", "info": "Dodatkowe komentarze:" },
        { "heading": "Głosowanie", "copy": "submitOuter" },
        { "field": "G1", "num": "G1", "pri": 1, "type": "bool+text", "text": "Czy w lokalu wyborczym lub terenie, na którym się on znajduje, zdarzył się przypadek agitacji wyborczej?", "info": "Jeśłi tak, to ile takich przypadków zauważyłaś/eś? Proszę opisać te przypadki." },
        { "field": "G2", "num": "G2", "pri": 1, "type": "bool+text", "text": "Czy zdarzyło się, że członkowie komisji nie sprawdzili komuś dokumentu tożsamości przed wydaniem kart do głosowania?", "info": "Jeśli tak, podaj liczbę takich przypadków." },
        { "field": "G3", "num": "G3", "pri": 1, "type": "bool+text", "text": "Czy członkowie komisji cały czas korzystali z osłony na dane osobowe?", "info": "Jeśli nie, podaj jak często z niej nie korzystali (sporadycznie, nagminnie, przez cały czas):" },
        { "field": "G4", "num": "G4", "pri": 1, "type": "bool+text", "text": "Czy urna była cały czas obserwowana?" },
        { "field": "G5", "num": "G5", "pri": 1, "type": "bool+text", "text": "Czy była osoba pełniąca rolę 'strażnika urny'?" },
        { "field": "G6", "num": "G6", "pri": 1, "type": "bool+text", "text": "Czy była przestrzegana tajność głosowania?", "info": "Jeśli nie, w jakich sytuacjach (np. tzw. głosowanie rodzinne, na widoku, inne) i czy nagminnie czy raczej sporadycznie:" },
        { "field": "G7", "num": "G7", "pri": 1, "type": "czestosc", "text": "Czy komisja interweniowała w przypadkach nieprzestrzegania lub naruszania tajności głosowania?" },
        { "field": "G8", "num": "G8", "pri": 1, "type": "bool+text", "text": "Czy strażnik urny lub komisja zawsze reagowała w sytuacji, gdy wyborca wrzucał do urny karty w sposób ujawniający na kogo oddał głos?", "info": "Jeśli reagowała, to w jaki sposób:" },
        { "field": "G9", "num": "G9", "pri": 1, "type": "bool+text", "text": "Czy wystąpiły jakiekolwiek problemy związane ze zbyt małą liczbą miejsc zapewniających tajność głosowania?", "info": "Jeśli tak, opisz jakie:" },
        { "field": "G10", "num": "G10", "pri": 1, "type": "bool+text", "text": "Czy zdarzyło się, że ktoś usiłował wynieść karty do głosowania z lokalu wyborczego?", "info": "Jeśli tak, podaj liczbę takich przypadków i opisz jak zareagowała Komisja:" },
        { "field": "G11", "num": "G11", "pri": 1, "type": "bool+text", "text": "Czy komisja w dowolnym momencie utrudniała Ci obserwację procesu głosowania?" },
        { "field": "G12", "num": "G12", "pri": 1, "type": "bool+text", "text": "Czy zgłaszałeś komisji uwagi do sposobu jej pracy?" },
        { "field": "G13", "num": "G13", "pri": 1, "type": "textarea", "text": "Jeżeli były takie przypadki, to jak reagowała komisja w sytuacji przybycia nazbyt dużej ilości głosujących?", "info": "Opisz pracę Komisji w godzinach największego obciążenia (jednoczesne przybycie nazbyt dużej ilości głosujących):" },
        { "field": "G14", "num": "G14", "pri": 1, "type": "ocena", "text": "Ogólna ocena pracy komisji podczas głosowania" },
        { "field": "G15", "num": "G15", "pri": 1, "type": "textarea", "text": "Dodatkowe komentarze (dot. głosowania)", "info": "Dodatkowe komentarze:" },
        { "heading": "Liczenie głosów", "copy": "submitOuter" },
        { "field": "L1", "num": "L1", "pri": 1, "type": "bool+text", "text": "Czy urna była zaplombowana w momencie, gdy komisja przystąpiła do jej otwierania?" },
        { "field": "L2", "num": "L2", "pri": 1, "type": "bool+text", "text": "Czy wszyscy członkowie komisji byli obecni w trakcie liczenia?", "info": "Jeżeli nie, opisz kto był nieobecny:" },
        { "field": "L3", "num": "L3", "pri": 1, "type": "bool+text", "text": "Czy komisja przeglądała, segregowała i liczyła karty i głosy działając wspólnie, nie dzieląc się na grupy?", "info": "Opisz sposób pracy komisji:" },
        { "field": "L4", "num": "L4", "pri": 1, "type": "bool+text", "text": "Czy w urnie znajdowały się materiały inne niż opieczętowane karty do głosowania?", "info": "Jeżeli tak, to co to było?" },
        { "field": "L5", "num": "L5", "pri": 1, "type": "bool+text", "text": "Czy wystąpiły jakiekolwiek problemy z interpretacją ważności głosów?", "info": "Opisz, na czym polegały problemy:" },
        { "field": "L6", "num": "L6", "pri": 1, "type": "niebylo3t", "text": "Czy w przypadku sporów dotyczących ważności głosu komisja podejmowała decyzję większością głosów?", "info": "Jeżeli nie, to opisz jak decydowała Komisja:" },
        { "field": "L7", "num": "L7", "pri": 1, "type": "bool+text", "text": "Czy wystąpiły jakiekolwiek problemy lub nieprawidłowości przy wypełnianiu protokołu?", "info": "Jeżeli tak, opisz je:" },
        { "field": "L8", "num": "L8", "pri": 1, "type": "bool+text", "text": "Czy mężowie zaufania lub członkowie komisji wnieśli uwagi do protokołu komisji?", "info": "Jeżeli tak, opisz jakie:" },
        { "field": "L9", "num": "L9", "pri": 1, "type": "bezuwag3t", "text": "Czy komisja ustosunkowała się do tych uwag?", "info": "Jeżeli tak, to w jaki sposób:" },
        { "field": "L10", "num": "L10", "pri": 1, "type": "niewiem3t", "text": "Czy wystąpiły jakiekolwiek problemy z wprowadzeniem danych do informatycznego systemu WOW", "info": "Jeżeli tak, to jakie?" },
        { "field": "L11", "num": "L11", "pri": 1, "type": "bool+text", "text": "Czy zdarzył się jakikolwiek przypadek odmowy wydania kopii protokołu mężowi zaufania lub obserwatorowi, jeśli o nią poprosił?" },
        { "field": "L12", "num": "L12", "pri": 1, "type": "bool+text", "text": "Czy komisja wywiesiła w miejscu łatwo dostępnym dla wyborców kopie protokołów głosowania w obwodzie?" },
        { "field": "L13", "num": "L13", "pri": 1, "type": "bool+text", "text": "Czy komisja w jakimkolwiek momencie utrudniała Ci obserwację procesu liczenia głosów?", "info": "Jeśli tak, jakie uwagi i jaka była reakcja członków Komisji?" },
        { "field": "L14", "num": "L14", "pri": 1, "type": "bool+text", "text": "Czy zgłaszałeś komisji uwagi do sposobu jej pracy?", "info": "Jeśli tak, opisz na czym polegały utrudnienia:" },
        { "field": "L15", "num": "L15", "pri": 1, "type": "text", "text": "O której godzinie komisja zakończyła pracę?" },
        { "field": "L16", "num": "L16", "pri": 1, "type": "ocena", "text": "Ogólna ocena pracy komisji podczas liczenia głosów" },
        { "field": "L17", "num": "L17", "pri": 1, "type": "textarea", "text": "Dodatkowe komentarze (liczenie głosów)", "info": "Dodatkowe komentarze:" },
        { "heading": "Klauzula dot. ochrony danych osobowych", "copy": "submitOuter" },
        { "field": "rodo", "num": "R0", "pri": 1, "ro": 1, "type": "info", "text": "Informacja o przetwarzaniu danych osobowych (RODO)", "info": """Zgodnie z art. 13 ust. 1 i ust. 2 ogólnego rozporządzenia o ochronie danych osobowych z dnia 27 kwietnia 2016 r. informujemy, iż: 
  1. Administratorem Pani/Pana danych osobowych jest Komitet Obrony Demokracji z siedzibą w Warszawie 01-144; Górczewska 39 
  2. Inspektorem ochrony danych w Komitecie Obrony Demokracji jest Pani Beata Somerschaf,
   e-mail: Beata.Somerschaf@ruchkod.pl 
  3. Pani/Pana dane osobowe przetwarzane za pomocą tego formularza będą użyte w projekcie Obywatelska Kontrola Wyborów podczas Wyborów Parlamentarnych 2019 r oraz informacji o działaniach Stowarzyszenia Komitet Obrony Demokracji) na podstawie art. 6 ust 1 pkt a ROZPORZĄDZENIE PARLAMENTU EUROPEJSKIEGO I RADY (UE) 2016/679 
  4. Pani/Pana dane osobowe nie będą przekazywane do państwa trzeciego/organizacji międzynarodowej 
  5. Pani/Pana dane osobowe będą przechowywane przez okres 5 lat 
  6. Posiada Pani/Pan prawo dostępu do treści swoich danych oraz prawo ich sprostowania, usunięcia, ograniczenia przetwarzania, prawo do przenoszenia danych, prawo wniesienia sprzeciwu, prawo do cofnięcia zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej cofnięciem 
  7. Ma Pan/Pani prawo wniesienia skargi do GIODO gdy uzna Pani/Pan, iż przetwarzanie danych osobowych Pani/Pana dotyczących narusza przepisy ogólnego rozporządzenia o ochronie danych osobowych z dnia 27 kwietnia 2016 r. 
  8. Podanie przez Pana/Panią danych osobowych jest warunkiem umownym. Jest Pan/Pani zobowiązana do ich podania a konsekwencją niepodania danych osobowych będzie brak możliwości udziału w projekcie.""" }
    ]
}

# def_ankieta = {
#     numer: 1,
#     data: {
#         rola: { n: 3, t: " " },
#         imie: "",
#         nazwisko: "",
#         czas_obserwacji_start: "08:00",
#         czas_obserwacji_end: "08:00",
#         obserwacja_przyg_lokalu: false,
#         obserwacja_glosowania: false,
#         obserwacja_liczenia: false,
#         woj: "",
#         gmina: "",
#         num_obw: "",
#         adres: "",
#         siedziba_opis: "",
#         komisja_czlonkow: "",
#         komisja_osob_upr: 0,
#         rodo: " ",
#         P1: { b: false, t: "" },
#         P2: { b: false, t: "" },
#         P3: { b: false, t: "" },
#         P4: { b: false, t: "" },
#         P5: { b: false, t: "" },
#         P6: { b: false, t: "" },
#         P7: { b: false, t: "" },
#         P8: { n: 0, t: "" },
#         P9: "",
#         G1: { b: false, t: "" },
#         G2: { b: false, t: "" },
#         G3: { b: false, t: "" },
#         G4: { b: false, t: "" },
#         G5: { b: false, t: "" },
#         G6: { b: false, t: "" },
#         G7: { n: 0, t: "" },
#         G8: { b: false, t: "" },
#         G9: { b: false, t: "" },
#         G10: { b: false, t: "" },
#         G11: { b: false, t: "" },
#         G12: { b: false, t: "" },
#         G13: "",
#         G14: { n: 0, t: "" },
#         G15: "",
#         L1: { b: false, t: "" },
#         L2: { b: false, t: "" },
#         L3: { b: false, t: "" },
#         L4: { b: false, t: "" },
#         L5: { b: false, t: "" },
#         L6: { v: "", t: "" },
#         L7: { b: false, t: "" },
#         L8: { b: false, t: "" },
#         L9: { v: "", t: "" },
#         L10: { v: "", t: "" },
#         L11: { b: false, t: "" },
#         L12: { b: false, t: "" },
#         L13: { b: false, t: "" },
#         L14: { b: false, t: "" },
#         L15: "",
#         L16: { n: 0, t: "" },
#         L17: ""
#     }
# }

# entries_data_okw = {
#     "1:020101:2": {
#         numer: 1,
#         data: {
#             imie: "Anna",
#             nazwisko: "Belska",
#             czas_obserwacji_start: "20:00",
#             czas_obserwacji_end: "21:00",
#             obserwacja_przyg_lokalu: "tak",
#             obserwacja_glosowania: "tak",
#             obserwacja_liczenia: "tak",
#             gmina: "Boles",
#             num_obw: "2",
#             siedziba: "Szk",
#             siedziba_opis: "Sala 22",
#             komisja_czlonkow: "7",
#             komisja_osob_upr: 800,
#             P1: "",
#             P2: "",
#             P3: "",
#             P4: "",
#             P5: "",
#             P6: "",
#             P7: "",
#             P8: "",
#             P9: "",
#             G1: "",
#             G2: "",
#             G3: "",
#             G4: "",
#             G5: "",
#             G6: "",
#             G7: "",
#             G8: "",
#             G9: "",
#             G10: "",
#             G11: "",
#             G12: "",
#             G13: "",
#             G14: "",
#             G15: "",
#             L1: "",
#             L2: "",
#             L3: "",
#             L4: "",
#             L5: "",
#             L6: "",
#             L7: "",
#             L8: "",
#             L9: "",
#             L10: "",
#             L11: "",
#             L12: "",
#             L13: "",
#             L14: "",
#             L15: ""
#         }
#     }
# };